import {
  Smartphone,
  Tablet,
  Laptop,
  Tv,
  Headphones,
  RotateCw,
  Watch,
  Newspaper,
  Zap,
} from 'lucide-react';

export const fallbackBrands: Record<string, string[]> = {
  'dien-thoai': [
    'Apple',
    'Samsung',
    'Xiaomi',
    'OPPO',
    'realme',
    'Honor',
    'Vertu',
    'TECNO',
  ],
  'ipad-tablet': ['Apple', 'Samsung', 'Xiaomi', 'Lenovo', 'Huawei'],
  'macbook-laptop': ['Apple', 'Asus', 'HP', 'Lenovo', 'Dell', 'Acer', 'MSI'],
  smartwatch: ['Apple', 'Samsung', 'Huawei', 'Xiaomi', 'Garmin'],
  'phu-kien': [
    'Anker',
    'Apple',
    'Baseus',
    'JBL',
    'Sony',
    'Innostyle',
    'Spigen',
    'UAG',
  ],
  'thiet-bi-am-thanh': [
    'JBL',
    'Marshall',
    'Sony',
    'Apple',
    'Anker',
    'Harman Kardon',
  ],
  'may-cu-gia-re': ['Apple', 'Samsung', 'Xiaomi', 'Oppo'],
  'gia-dung': ['Xiaomi', 'Deerma', 'Philips', 'Bear', 'Tefal'],
  'thu-cu-doi-moi-trade-in': ['Apple', 'Samsung', 'Xiaomi', 'OPPO'],
};

export const fallbackHotSeries: Record<string, string[]> = {
  'dien-thoai': [
    'iPhone 16 Series',
    'iPhone 15 Series',
    'Galaxy S25 Series',
    'Galaxy Z Flip7',
    'Xiaomi 15T Pro',
    'Redmi Note 14',
    'OPPO Reno14',
    'OPPO A6 Pro',
  ],
  'ipad-tablet': [
    'iPad Pro M4',
    'iPad Air M2',
    'iPad Gen 10',
    'Galaxy Tab S10 Ultra',
    'Galaxy Tab S9 FE',
    'Galaxy Tab A9+',
  ],
  'macbook-laptop': [
    'MacBook Pro M3',
    'MacBook Air M3',
    'Asus ROG Gaming',
    'Asus Zenbook',
    'HP Pavilion',
    'Dell Inspiron',
    'Lenovo ThinkPad',
  ],
  smartwatch: [
    'Apple Watch Ultra 2',
    'Apple Watch Series 10',
    'Apple Watch SE',
    'Galaxy Watch Ultra',
    'Galaxy Watch7',
    'Huawei Watch GT5',
  ],
  'phu-kien': [
    'Sạc nhanh GaN 65W',
    'Cáp sạc chống đứt',
    'Ốp lưng UAG cao cấp',
    'Kính cường lực Kingbull',
    'Giá đỡ điện thoại',
  ],
  'thiet-bi-am-thanh': [
    'AirPods Pro 2',
    'JBL Tour Pro 2',
    'Loa Bluetooth JBL Go 4',
    'Loa Marshall Acton III',
    'Sony WH-1000XM5',
  ],
  'may-cu-gia-re': [
    'iPhone 15 Pro Max cũ',
    'iPhone 14 Pro Max cũ',
    'iPhone 13 Pro Max cũ',
    'Galaxy S24 Ultra cũ',
    'iPad Pro cũ',
  ],
  'gia-dung': [
    'Robot hút bụi Xiaomi',
    'Máy lọc không khí Xiaomi',
    'Nồi chiên không dầu',
    'Máy tăm nước',
    'Ấm siêu tốc',
  ],
  'thu-cu-doi-moi-trade-in': [
    'Thu cũ iPhone 16 Pro Max',
    'Thu cũ iPhone 15 Pro Max',
    'Thu cũ Galaxy S24 Ultra',
    'Thu cũ iPhone 14 Pro Max',
  ],
};

export const sidebarMenuItems = [
  {
    name: 'Điện thoại di động',
    slug: 'dien-thoai',
    dbSlug: 'dien-thoai',
    icon: Smartphone,
  },
  {
    name: 'iPad & Tablet',
    slug: 'ipad-tablet',
    dbSlug: 'ipad-tablet',
    icon: Tablet,
  },
  {
    name: 'MacBook & Laptop',
    slug: 'macbook-laptop',
    dbSlug: 'macbook-laptop',
    icon: Laptop,
  },
  {
    name: 'Máy cũ giá rẻ',
    slug: 'may-cu-gia-re',
    dbSlug: 'may-cu-gia-re',
    icon: RotateCw,
  },
  {
    name: 'Phụ kiện công nghệ',
    slug: 'phu-kien',
    dbSlug: 'phu-kien',
    icon: Headphones,
  },
  {
    name: 'Đồng hồ thông minh',
    slug: 'smartwatch',
    dbSlug: 'smartwatch',
    icon: Watch,
  },
  {
    name: 'Âm thanh',
    slug: 'am-thanh',
    dbSlug: 'thiet-bi-am-thanh',
    icon: Headphones,
  },
  {
    name: 'Điện máy, Gia dụng',
    slug: 'gia-dung',
    dbSlug: 'gia-dung',
    icon: Tv,
  },
  {
    name: 'Thu cũ đổi mới',
    slug: 'trade-in',
    dbSlug: 'thu-cu-doi-moi-trade-in',
    icon: RotateCw,
  },
  {
    name: 'Voucher khuyến mãi',
    slug: 'vouchers',
    isStatic: true,
    icon: Zap,
    link: '/vouchers',
  },
  {
    name: 'Tin tức công nghệ',
    slug: 'blogs',
    isStatic: true,
    icon: Newspaper,
    link: '/blogs',
  },
];
